const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
window.addEventListener('load',()=>setTimeout(()=>$('#loader')?.classList.add('done'),900));
const progress=$('.progress i');
function updateProgress(){const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h>0?(scrollY/h)*100:0)+'%'} addEventListener('scroll',updateProgress,{passive:true});updateProgress();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(x=>observer.observe(x));
const cursor=$('.cursor-glow'),dot=$('.cursor-dot');let mx=0,my=0,cx=0,cy=0;addEventListener('pointermove',e=>{mx=e.clientX;my=e.clientY});function cursorLoop(){cx+=(mx-cx)*.16;cy+=(my-cy)*.16;if(cursor){cursor.style.left=cx+'px';cursor.style.top=cy+'px'}if(dot){dot.style.left=mx+'px';dot.style.top=my+'px'}requestAnimationFrame(cursorLoop)}cursorLoop();
$$('a,.project,.skill-items b,.experience-card').forEach(el=>{el.addEventListener('mouseenter',()=>{if(cursor){cursor.style.width='500px';cursor.style.height='500px'}});el.addEventListener('mouseleave',()=>{if(cursor){cursor.style.width='420px';cursor.style.height='420px'}})});
$$('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.16,y=(e.clientY-r.top-r.height/2)*.16;el.style.transform=`translate3d(${x}px,${y}px,0)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
$$('.tilt-card').forEach(card=>{const inner=$('.portrait-frame,.about-image',card)||card;card.addEventListener('pointermove',e=>{if(matchMedia('(max-width:900px)').matches)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5,p=+card.dataset.tilt||12;inner.style.transform=`rotateX(${-y*p}deg) rotateY(${x*p}deg) translateZ(8px)`});card.addEventListener('pointerleave',()=>inner.style.transform='')});
$$('.tilt-row').forEach(row=>{row.addEventListener('pointermove',e=>{if(matchMedia('(max-width:900px)').matches)return;const r=row.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5;row.style.transform=`perspective(900px) rotateY(${x*2}deg) translateX(${x*5}px)`});row.addEventListener('pointerleave',()=>row.style.transform='')});
$$('.project').forEach(card=>card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;card.style.setProperty('--mx',x+'%');card.style.setProperty('--my',y+'%');if(!matchMedia('(max-width:900px)').matches){card.style.transform=`perspective(1000px) rotateX(${-(y-50)*.035}deg) rotateY(${(x-50)*.035}deg) translateY(-5px)`}}));$$('.project').forEach(card=>card.addEventListener('pointerleave',()=>card.style.transform=''));
const menu=$('.menu'),mobileNav=$('.mobile-nav');menu?.addEventListener('click',()=>{const open=mobileNav.classList.toggle('open');menu.setAttribute('aria-expanded',open);mobileNav.setAttribute('aria-hidden',!open)});$$('.mobile-nav a').forEach(a=>a.addEventListener('click',()=>{mobileNav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const sections=$$('main section[id]'),navLinks=$$('.nav nav a');const navObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-35% 0px -55% 0px'});sections.forEach(s=>navObs.observe(s));
// Real projects will be inserted here later. No placeholder projects are fabricated.
const projects=[];const grid=$('#project-grid'),empty=$('#work-empty');function renderProjects(){if(!grid)return;grid.innerHTML='';empty.hidden=projects.length>0;projects.forEach((p,i)=>{const card=document.createElement('article');card.className='project reveal';card.innerHTML=`<div class="project-visual" ${p.image?`style="background-image:linear-gradient(180deg,transparent 30%,rgba(0,0,0,.8)),url('${p.image}');background-size:cover;background-position:center"`:''}><span>${p.category||`PROJECT ${String(i+1).padStart(2,'0')}`}</span></div><div class="project-info"><h3>${p.title}</h3><p>${p.description||''}</p></div>`;if(p.link)card.onclick=()=>window.open(p.link,'_blank','noopener');grid.appendChild(card);observer.observe(card)})}renderProjects();
// Three.js: subtle floating red particle/geometry field for depth and motion.
(function(){if(!window.THREE||matchMedia('(prefers-reduced-motion:reduce)').matches)return;const host=$('#scene');const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,100);camera.position.z=7;const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);host.appendChild(renderer.domElement);const group=new THREE.Group();scene.add(group);const geo=new THREE.IcosahedronGeometry(.12,1),mat=new THREE.MeshBasicMaterial({color:0xff263d,wireframe:true,transparent:true,opacity:.42});for(let i=0;i<28;i++){const m=new THREE.Mesh(geo,mat);m.position.set((Math.random()-.5)*12,(Math.random()-.5)*8,(Math.random()-.5)*5);m.rotation.set(Math.random()*3,Math.random()*3,Math.random()*3);m.scale.setScalar(.5+Math.random()*1.8);group.add(m)}const lineMat=new THREE.LineBasicMaterial({color:0xff263d,transparent:true,opacity:.08});for(let i=0;i<6;i++){const pts=[];for(let j=0;j<12;j++)pts.push(new THREE.Vector3(-6+j,Math.sin(j*.7+i)*.7-2+i*.7, -2+i*.3));group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),lineMat))}let targetX=0,targetY=0;addEventListener('pointermove',e=>{targetX=(e.clientX/innerWidth-.5)*.35;targetY=(e.clientY/innerHeight-.5)*.25});function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}addEventListener('resize',resize);let t=0;function animate(){t+=.003;group.rotation.y+=(targetX-group.rotation.y)*.015;group.rotation.x+=(targetY-group.rotation.x)*.015;group.position.y=Math.sin(t*2)*.08;group.children.forEach((m,i)=>{if(m.isMesh){m.rotation.x+=.002+i*.00003;m.rotation.y+=.003}});renderer.render(scene,camera);requestAnimationFrame(animate)}animate()})();

/* Immersive project showcase engine */
const projectData=[
 {category:'CINEMATIC',title:'Project Slot 01',description:'Your strongest cinematic edit — presented as a layered 3D media experience.',role:'Editor / Creative',format:'Cinematic video',video:'',link:''},
 {category:'SHORT-FORM',title:'Project Slot 02',description:'A high-impact reel or short-form edit with a motion-first preview and case-study reveal.',role:'Editor / Content',format:'Reel / Short',video:'',link:''},
 {category:'BRAND',title:'Project Slot 03',description:'A real promotional or client project with its final video, creative role and published link.',role:'Editor / Creator',format:'Brand content',video:'',link:''},
 {category:'CONTENT',title:'Project Slot 04',description:'A real content piece, YouTube edit or social campaign shown through an immersive project view.',role:'Editor / Videographer',format:'Digital content',video:'',link:''}
];
const projectGrid=$('#project-grid');
function renderProjects(){if(!projectGrid)return;projectGrid.innerHTML=projectData.map((p,i)=>`<button class="project-card reveal" type="button" data-project="${i}" aria-label="Open ${p.title} case study"><span class="media-tag">${p.video?'VIDEO PREVIEW':'MEDIA READY'}</span><div class="project-card-inner"><div class="project-media"><div class="project-media-grid"></div><div class="project-orbit"><i></i></div><div class="project-label"><small>${p.category}</small>${p.title.toUpperCase()}</div><span class="project-number">0${i+1} / 04</span></div><div class="project-content"><h3>${p.title}</h3><p>${p.description}</p><span class="project-open">↗</span></div></div></button>`).join('');
 projectGrid.querySelectorAll('.project-card').forEach((card)=>{
   card.addEventListener('pointermove',e=>{if(matchMedia('(hover: hover) and (pointer: fine)').matches){const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;card.style.setProperty('--ry',`${(x-.5)*10}deg`);card.style.setProperty('--rx',`${(.5-y)*10}deg`);card.style.setProperty('--px',`${x*100}%`);card.style.setProperty('--py',`${y*100}%`);}});
   card.addEventListener('pointerleave',()=>{card.style.setProperty('--ry','0deg');card.style.setProperty('--rx','0deg');card.style.setProperty('--px','50%');card.style.setProperty('--py','50%');});
   card.addEventListener('click',()=>openCase(Number(card.dataset.project)));
 });
 observer&&projectGrid.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
}
const caseStudy=$('#case-study'),caseVideo=$('#case-video');
function openCase(i){const p=projectData[i]||projectData[0];$('#case-category').textContent=p.category;$('#case-index').textContent=`0${i+1} / 04`;$('#case-title').textContent=p.title;$('#case-description').textContent=p.description;$('#case-role').textContent=p.role;$('#case-format').textContent=p.format;$('#case-media-label').textContent=p.title.toUpperCase();const link=$('#case-link');if(p.link){link.href=p.link;link.style.display='inline-flex'}else{link.removeAttribute('href');link.style.display='none'}if(p.video){caseVideo.src=p.video;$('#case-media').classList.add('has-video');caseVideo.play().catch(()=>{})}else{caseVideo.pause();caseVideo.removeAttribute('src');caseVideo.load();$('#case-media').classList.remove('has-video')}caseStudy.classList.add('open');caseStudy.setAttribute('aria-hidden','false');document.body.classList.add('case-open');$('.case-close')?.focus();}
function closeCase(){caseStudy?.classList.remove('open');caseStudy?.setAttribute('aria-hidden','true');document.body.classList.remove('case-open');caseVideo?.pause();}
caseStudy?.querySelectorAll('[data-close-case]').forEach(x=>x.addEventListener('click',closeCase));
addEventListener('keydown',e=>{if(e.key==='Escape'&&caseStudy?.classList.contains('open'))closeCase()});
renderProjects();
